Python Assignment - II

Inheritance and Its types

Single Inheritance

In [6]:
class base(object): 
       
    # Constructor 
    def __init__(fly, value1,value2): 
        fly.value1 = value1 
        fly.value2 = value2
   
    # To perform addition
    def Addition(fly) : 
        print(" value1 : " , fly.value1)
        print(" value2 : " , fly.value2)
        return fly.value1 + fly.value2
              
# derived class or the sub class
class Derived(base): 
    
    #function to perform addition
   def subraction(fly) :
        print(" value1 : " , fly.value1)
        print(" value2 : " , fly.value2)
        return fly.value1 - fly.value2
      
# Driver code 
Obj = Child_class(10,15)  # parent class object
print(" Added value :" , Obj.Addition() ) 
print( " " )
Obj1 = Child_class(50,30)  # parent class object
print("Subracted value :" , Obj1.subraction() ) 

 value1 :  10
 value2 :  15
 Added value : 25
 
 value1 :  50
 value2 :  30
Subracted value : 20


MULTIPLE INHERITANCE

In [8]:
class Mother:
    mothername = ""
 
    def mother(self):
        print(self.mothername)
 
 
class Father:
    fathername = ""
 
    def father(self):
        print(self.fathername)
 
 
class Son(Mother, Father):
    def parents(self):
        print("Father Name :", self.fathername)
        print("Mother  Name:", self.mothername)
 
 
# Driver's code
s1 = Son()
s1.fathername = "Murugan"
s1.mothername = "Visalatchi"
s1.parents()

Father Name : Murugan
Mother  Name: Visalatchi


MULTILEVEL INHERITANCE

In [12]:
class Animal:  
    def speak(self):  
        print("Animal Speaking")  
 
class Dog(Animal):  
    def bark(self):  
        print("dog barking")  
  
class DogChild(Dog):  
    def eat(self):  
        print("Eating bread...")  
d = DogChild()  
d.bark()  
d.speak()  
d.eat()  

dog barking
Animal Speaking
Eating bread...


HYBRID INHERITANCE

In [27]:
class home:
    def func1(self):
        print("This function is in home.")
 
 
class school(home):
    def func2(self):
        print("This function is in school. ")
 
 
class tuition(home):
    def func3(self):
        print("This function is in tuition.")
 
 
class playground(school, home):
    def func4(self):
        print("This function is in playground🤩.")
 
obj = child()
obj.func1()
obj.func2()

This function is in home.
This function is in school. 


HIERARCHICAL INHERITANCE

In [28]:
class Parent:
    def func1(self):
        print("This function is in parent class.")
 
 
class Child1(Parent):
    def func2(self):
        print("This function is in child 1.")
 
 
class Child2(Parent):
    def func3(self):
        print("This function is in child 2.")
 
object1 = Child1()
object2 = Child2()
object1.func1()
object1.func2()
object2.func1()
object2.func3()

This function is in parent class.
This function is in child 1.
This function is in parent class.
This function is in child 2.


EXCEPTION HANDLING

ZerroDivisonal error

In [29]:
def fun(a):
    if a < 4:
        b = a/(a-3)
    print("Value of b = ", b) 
try:
    fun(3)
    fun(5)
  
 
# multiple exceptions
except ZeroDivisionError:
    print("ZeroDivisionError Occurred and Handled")

ZeroDivisionError Occurred and Handled


TAB ERROR

In [31]:
a = [1, 2, 3]
try: 
    print ("Second element = %d" %(a[1]))
  
    # Throws error since there are only 3 elements in array
    print ("Fourth element = %d" %(a[3]))
  
except:
    print ("An error occurred")

Second element = 2
An error occurred


VALUE ERROR

In [36]:
while True:
...     try:
...         x = int(input("Please enter a number: "))
...         break
...     except ValueError:
...         print("Oops!  That was no valid number.  Try again...")
...


Please enter a number: 788


 FILE OPENING ERROR

In [37]:
try:
  f = open("demofile.txt")
  try:
    f.write("Lorum Ipsum")
  except:
    print("Something went wrong when writing to the file")
  finally:
    f.close()
except:
  print("Something went wrong when opening the file")

Something went wrong when opening the file


INDENTATION ERROR

In [53]:
a = 10
try:
     b = 19
     c = a+b
except:
    print("indentation error is occured")
print(c)



29


NAME ERROR

In [54]:
try:
  print(s)
except NameError:
  print("Variable s is not defined")
except:
  print("Something else went wrong")

Variable s is not defined


                                            REGULAR EXPRESSION

FINDALL()

In [56]:
import re

word = "python is a interrepted language"
x = re.findall("is", word)
print(x)

['is']


SEARCH()

In [57]:
import re

fly = "This is beautiful world "
x = re.search("\s", fly)

print("The located in position:", x.start())

The located in position: 4


SPLIT()

In [58]:
import re

sen = "PYTHON IS A INTEREPTED LANGUAGE"
x = re.split("\s", sen)
print(x)

['PYTHON', 'IS', 'A', 'INTEREPTED', 'LANGUAGE']


SUB()

In [60]:
import re
part = "PYTHON IS A INTEREPTED LANGUAGE"
x = re.sub("\s", "n", part)
print(x)

PYTHONnISnAnINTEREPTEDnLANGUAGE


                                            AGRREGATE FUNCTIONS

In [63]:
import numpy as np
arr1 = np.array([10,20,30,40,50])
arr1
b = np.array([20,34,45,56,78])
print(b)

[20 34 45 56 78]


In [75]:
FLY = np.array([[0,10,20],[3,4,50],[90,40,50]])
FLY

array([[ 0, 10, 20],
       [ 3,  4, 50],
       [90, 40, 50]])

SUM FUNCTION

In [76]:
arr1.sum()

150

In [77]:
FLY.sum(axis=0)

array([ 93,  54, 120])

In [78]:
FLY.sum(axis=1)

array([ 30,  57, 180])

PRODUCT FUNCTION

In [79]:
np.prod(arr1)

12000000

In [80]:
np.prod(FLY,axis=0)

array([    0,  1600, 50000])

In [81]:
np.prod(FLY,axis=1)

array([     0,    600, 180000])

AVERAGE FUNCTION

In [82]:
np.average(FLY,axis = 1)

array([10., 19., 60.])

In [83]:
np.average(FLY,axis = 0)

array([31., 18., 40.])

MINIMUM FUNCTION

In [84]:
FLY.min(axis = 0)

array([ 0,  4, 20])

In [85]:
FLY.min(axis = 1)

array([ 0,  3, 40])

MAXIMUM FUNCTION

In [86]:
FLY.max(axis = 0)

array([90, 40, 50])

In [87]:
FLY.max(axis = 1)

array([20, 50, 90])

In [88]:
import numpy as np
x = np.random.randint(1, 10, size = (5, 5))
print(x)
print()
 
y = np.random.randint(1, 10, size = (5, 5))
print(y)
 
print('\nMinimum Array')
print(np.minimum(x, y))

[[7 7 7 9 6]
 [6 5 8 5 4]
 [8 4 6 6 1]
 [8 5 6 5 4]
 [1 3 5 2 6]]

[[9 8 2 1 8]
 [6 5 7 1 6]
 [3 4 9 2 8]
 [3 2 8 5 9]
 [6 8 4 4 7]]

Minimum Array
[[7 7 2 1 6]
 [6 5 7 1 4]
 [3 4 6 2 1]
 [3 2 6 5 4]
 [1 3 4 2 6]]


In [89]:
import numpy as np
 
a = np.array([1, 20, 5, 22, 8, 15])
print(a)

b = np.array([12, 9, 3, 42, 6, 33])
print(b)
 
print('\nMaximum Array')
print(np.maximum(a, b))

[ 1 20  5 22  8 15]
[12  9  3 42  6 33]

Maximum Array
[12 20  5 42  8 33]


MEDIAN FUNCTION

In [90]:
np.median(FLY)
np.median(FLY)

np.median(FLY, axis = 0)
np.median(FLY, axis = 1)


array([10.,  4., 50.])

VARIANCE FUNCTION

In [91]:
arr1.var()
FLY.var()


x.var()
y.var()

6.8

CUMULATIVE SUM

In [92]:
arr1.cumsum()
arr2.cumsum()

array([  0,  10,  30,  50,  90, 140, 170, 210, 260], dtype=int32)

CUMULATIVE PRODUCT

In [94]:
arr1.cumprod()
FLY.cumprod()
 

# Let me find the cumulative product of array elements in x and Y axis
FLY.cumprod(axis = 0)
FLY.cumprod(axis = 1)

array([[     0,      0,      0],
       [     3,     12,    600],
       [    90,   3600, 180000]], dtype=int32)

PERCENTILE FUNCTION

In [96]:
np.percentile(FLY, 10)
np.percentile(FLY, 30)
np.percentile(FLY, 50)
np.percentile(FLY, 75)
np.percentile(FLY, 100)

90.0

ARGMIN FUNCTION

In [98]:
arr4 = np.random.randint(10, size = (9))
arr4

arr5 = np.random.randint(8, size = (5, 5))
arr5


array([[4, 1, 3, 7, 3],
       [4, 5, 1, 4, 4],
       [5, 6, 3, 2, 6],
       [0, 0, 1, 1, 2],
       [3, 2, 6, 5, 7]])